### PR TITLE
Handle gerrors

### LINKED ISSUE #222: Unreachable code reached in value.cc for GI_TYPE_TAG_ERROR
Same case as #221, when closing the window.

We're not handling GI_TYPE_TAG_ERROR in that switch statement.

```
** (node:1742852): CRITICAL **: 08:13:53.238: Tag: error
**
ERROR:../src/value.cc:167:v8::Local<v8::Value> GNodeJS::GIArgumentToV8(GITypeInfo*, GIArgument*, long int, bool): code should not be reached
Bail out! ERROR:../src/value.cc:167:v8::Local<v8::Value> GNodeJS::GIArgumentToV8(GITypeInfo*, GIArgument*, long int, bool): code should not be reached
--Type <RET> for more, q to quit, c to continue without paging--

Thread 1 "node" received signal SIGABRT, Aborted.
0x00007ffff7aa0615 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7aa0615 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff7a89862 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff5004084 in  () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff505e8cd in g_assertion_message_expr () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff52063bf in GNodeJS::GIArgumentToV8(_GIBaseInfoStub*, _GIArgument*, long, bool) (type_info=0x7fffffffaea0, arg=0x4a79288, length=-1, mustCopy=false) at ../src/value.cc:167
#5  0x00007ffff51f8f80 in GNodeJS::FunctionInfo::GetReturnValue(v8::Local<v8::Value>, _GIBaseInfoStub*, _GIArgument*, _GIArgument*)
    (this=0x47f80b0, self=..., return_type=0x7fffffffb100, return_value=0x7fffffffb030, callable_arg_values=0x7fffffffaf88) at ../src/function.cc:608
#6  0x00007ffff51f7b95 in GNodeJS::FunctionCall(GNodeJS::FunctionInfo*, Nan::FunctionCallbackInfo<v8::Value> const&, _GIArgument*, _GError**)
    (func=0x47f80b0, info=..., return_value=0x0, error=0x0) at ../src/function.cc:303
#7  0x00007ffff51f9256 in GNodeJS::FunctionInvoker(Nan::FunctionCallbackInfo<v8::Value> const&) (info=...) at ../src/function.cc:654
#8  0x00007ffff51eb2ac in Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&) (info=...) at ../node_modules/nan/nan_callbacks_12_inl.h:176
```

### PR DESCRIPTION
**Pull request by wotzlaff**
We try to handle `GError`s.
The only problem I see is that we need to `g_error_copy` in `GErrorToV8`. This is necessary because it will get freed sometimes. However, it should be freed somewhere later (similarly to `g_base_unref` for `GObject`s) but I have no idea when and where.

I might also be wrong by using `Nan::SetInstanceTemplate` in `GErrorToV8`.

Fixes #222

### CODE REVIEW

**Comment by romgrk** [comment]
Lol I had written a big message and I navigated away and lost it ^^ Well I'll try to summarize:
 - I think GErrors look more like Boxeds than GObjects, so `GetClassTemplate` (which is for GObjects) is probably not what we want. More details on boxeds: https://developer.gnome.org/gobject/stable/gobject-Boxed-Types.html
 - All you need to read to understand the memory management of boxeds is here: https://github.com/romgrk/node-gtk/blob/master/src/boxed.cc#L157-L285
 - Basically, GType-registered boxeds can be copied and freed with `g_boxed_(copy|free)`
 - We keep additional info on them with our `Box`, and we attach them to a v8's WeakPointer. The WeakPointer notifies us (at `BoxedDestroyed`) when the JS object to which we've attached it is about to be GC'ed. Then we free the boxed.

As for `Nan::SetInstanceTemplate()`, that's probably not what we want. V8's templates are [blueprints for javascript functions](https://v8.dev/docs/embed#templates). I'm not super clear on all their terminology, but essentially a Function is an instance of a FunctionTemplate, and a Function can itself be instantiated to give JS object instances. I would probably suggest to use `Nan::Set(instance, key, value)` here.

**Comment by wotzlaff** [comment]
You are right. Boxed-like handling should be the way to go. Thanks for the references. I'll try to fix it.

**Comment by wotzlaff** [comment]
This should work now.
I had to use `Nan::DefineOwnProperty` instead of `Nan::Set` because it ran into [this error](https://github.com/romgrk/node-gtk/blob/master/src/gi.cc#L230) otherwise.

As always: I am not certain that `mustCopy = true` is the right thing to do here. Anyway, it seems necessary to set it explicitly.

**Comment by romgrk** [comment]
My comment [here](https://github.com/romgrk/node-gtk/pull/205#issuecomment-649824011) still applies. Unless the JS object absolutely needs to point to the same memory location as the C object, we copy. Only GObject and some very rare out-parameter Boxeds absolutely need to point to the same memory location. For the rest, we have no control when the C object is freed, therefore if we want to point to it we need to copy it. That is because the lifetime of the associated JS object is unknown and could very well outlast that of the C object.
Also the advantage of copying is that the danger is memory leaks, while the danger of not-copying is use-after-free & memory corruption. Memory leaks are easier to debug IMHO. Also as long as you carefully follow your objects and make sure they're freed you're ok.

Actually I've been thinking about it, and I'm not even sure we need to create a Boxed object here. We could simply create a plain Javascript object. If you read `GHashToV8` for example, we don't keep any reference to the original `GHashTable`: we simply create a plain JS object with the same key-values.
Until we find an example where modifying the JS object needs to modify the underlying GHashTable, that is a fine way to handle it.
EDIT: After investigation, let's not take the plain-object approach, because the object still needs to be an instance of Glib.Error

But for GError, I'm 99.9% sure that we don't want modifiable-c-objects behavior. That is because GError are used to pass information around (see again "value objects" from previous comment), as opposed to being used to store state.

------

Ok I've inspected more, and actually if you use the Boxed approach, you don't need to define the properties "code", "domain" and "message". That is because GErrors are indeed boxed. I've inspected it as follow:

```javascript
const inspect = require('./lib/inspect.js')
const glib = inspect.parseNamespace('GLib')
const GError = glib.Error

console.log(GError)
```

<details>
<summary>output</summary>
<ref *1> StructInfo {
  infoType: 'struct',
  name: 'Error',
  parent: 'GLib',
  gtype: 98352576,
  size: 16,
  alignment: 8,
  is_gtype_struct: false,
  is_foreign: false,
  constructor: FunctionInfo {
    infoType: 'function',
    name: 'new_literal',
    parent: [Circular *1],
    n_args: 3,
    args: [ [ArgInfo], [ArgInfo], [ArgInfo] ],
    transfer: 'EVERYTHING',
    return_type: TypeInfo {
      infoType: 'type',
      type: 'error',
      size: 8,
      isPointer: true
    },
    return_tag: 'error',
    symbol: 'g_error_new_literal',
    isMethod: 0,
    isConstructor: 0,
    isGetter: 0,
    isSetter: 0
  },
  methods: [Object: null prototype] {
    new_literal: FunctionInfo {
      infoType: 'function',
      name: 'new_literal',
      parent: [Circular *1],
      n_args: 3,
      args: [Array],
      transfer: 'EVERYTHING',
      return_type: [TypeInfo],
      return_tag: 'error',
      symbol: 'g_error_new_literal',
      isMethod: 0,
      isConstructor: 0,
      isGetter: 0,
      isSetter: 0
    },
    copy: FunctionInfo {
      infoType: 'function',
      name: 'copy',
      parent: [Circular *1],
      n_args: 0,
      args: [],
      transfer: 'EVERYTHING',
      return_type: [TypeInfo],
      return_tag: 'error',
      symbol: 'g_error_copy',
      isMethod: 1,
      isConstructor: 1,
      isGetter: 1,
      isSetter: 1
    },
    free: FunctionInfo {
      infoType: 'function',
      name: 'free',
      parent: [Circular *1],
      n_args: 0,
      args: [],
      transfer: 'NOTHING',
      return_type: [TypeInfo],
      return_tag: 'void',
      symbol: 'g_error_free',
      isMethod: 1,
      isConstructor: 1,
      isGetter: 1,
      isSetter: 1
    },
    matches: FunctionInfo {
      infoType: 'function',
      name: 'matches',
      parent: [Circular *1],
      n_args: 2,
      args: [Array],
      transfer: 'NOTHING',
      return_type: [TypeInfo],
      return_tag: 'gboolean',
      symbol: 'g_error_matches',
      isMethod: 1,
      isConstructor: 1,
      isGetter: 1,
      isSetter: 1
    }
  },
  fields: [Object: null prototype] {
    domain: FieldInfo {
      infoType: 'field',
      name: 'domain',
      parent: [Circular *1],
      type: 'guint32'
    },
    code: FieldInfo {
      infoType: 'field',
      name: 'code',
      parent: [Circular *1],
      type: 'gint32'
    },
    message: FieldInfo {
      infoType: 'field',
      name: 'message',
      parent: [Circular *1],
      type: 'utf8'
    }
  }
}
</details>

What this tells us is that the GError struct (aka boxed) already has those fields defined in it's prototype, therefore accessing `error.code` will query the field in the copied C object attached to the JS object. I can give more details but I feel this is already too long. Try it out with just creating the boxed with `WrapperFromBoxed` and let me know what happends.

```

**Comment by wotzlaff** [comment]
You are obviously right. The properties are already there through the prototype.
It bothers me a bit that the `console.log` output does not show them. So I always get confused. Maybe I should open an issue to fix that.

Also, thanks for your patience. I feel always like making more work than you would have done by fixing the issue on your own :sweat_smile:

**Comment by romgrk** [comment]
> The properties are already there through the prototype. It bothers me a bit that the console.log output does not show them.
They have the `enumerable` attribute set to `false`, as most of prototype field-accessors have

> Also, thanks for your patience. I feel always like making more work than you would have done by fixing the issue on your own
No it's good that I need to explain stuff, it allows me to validate that I *really* understand what's going on ^^ Besides I've already seen you writing code that I hadn't thought to write that way so don't worry your contributions are appreciated.

**Comment by romgrk** [comment]
LGTM 👍

File: tests/error.js [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+Gst.init()
+
+const ERROR_MESSAGE = 'ERROR_MESSAGE'
+const ERROR_CODE = 42
+const DEBUG_STRING = 'debug string'
+
+common.describe('GError', () => {
+  common.it('should be returned', () => {
+    common.assert(GLib.Error !== undefined)
+    const err0 = GLib.Error.newLiteral(404, ERROR_CODE, ERROR_MESSAGE)
```
Comment (sdroege) [inline tests/error.js:20]: Error domains are `GQuark`s and need to be registered as such. You shouldn't allow passing random integers in here or otherwise code will likely misbehave or crash. For example you should get back a proper string when calling `g_quark_to_string()` on it.

Comment (wotzlaff) [reply tests/error.js:20]: You are right. The testing is not done properly. It should be fixed through #227.
