### PR TITLE
Fix function call inout parameters

### LINKED ISSUE #231: Possible wrong return value of Gtk.init on macOS
We found this problem after solving build issues in #230.

The problem occurs in `tests/function_call_inout.js` and `tests/conversion__array.js` (basically the same issue in both tests).
`Gtk.init(['argument1', '--gtk-debug', 'misc', 'argument2'])` returns its arguments on macOS, but should return only `['argument1', 'argument2']`.

### LINKED ISSUE #235: g_base64_decode fails (function out parameters)
```javascript
const GLib = gi.require('GLib', '2.0');

const data = 'aGVsbG8='
const result = GLib.base64Decode(data, data.length)
// keeps running for a while; `out_len` parameter is likely corrupted because it returns a huge number 
```

### PR DESCRIPTION
**Pull request by romgrk**
Fixes #231 
Fixes #235

### CODE REVIEW

**Comment by romgrk** [comment]
I'm done with my modifications here. This PR does a bit more than what the title but it should be simple enough to understand. If anyone wants to review before I merge it would be nice, otherwise I'll merge tomorrow if the build passes. This should allow to create tha macOS binaries.

**Comment by wotzlaff** [comment]
I will have a look at it tomorrow.

**Comment by romgrk** [comment]
It feels so good for once to have green tests :angel:

File: src/type.cc [hunk 1]
```diff
@@ -281,5 +281,81 @@ GITypeTag GetStorageType (GITypeInfo *type_info) {
     return type_tag;
 }
 
+bool IsTypeSimple (GITypeInfo *type_info) {
```
Comment (wotzlaff) [inline src/type.cc:284]: We are not using this function anywhere, do we?
Maybe it should be added later when it's really needed.

File: src/function.cc [hunk 2]
```diff
@@ -558,18 +562,34 @@ Local<Value> FunctionInfo::GetReturnValue (
...
                                 jsReturnValue = (value);
 
+    int return_length_i = g_type_info_get_array_length(return_type);
+
     if (!ShouldSkipReturn(info, return_type)) {
         long length = -1;
-        int length_i = g_type_info_get_array_length(return_type);
-        if (length_i >= 0)
-            length = callable_arg_values[length_i].v_long;
+        int return_length_i = g_type_info_get_array_length(return_type);
```
Comment (wotzlaff) [inline src/function.cc:569]: This has already been done 4 lines above.

File: src/type.cc [hunk 3]
```diff
@@ -281,5 +281,81 @@ GITypeTag GetStorageType (GITypeInfo *type_info) {
...
+        case GI_TYPE_TAG_UINT16:
+        case GI_TYPE_TAG_INT32:
+        case GI_TYPE_TAG_UINT32:
+        case GI_TYPE_TAG_INT64:
+        case GI_TYPE_TAG_UINT64:
+        case GI_TYPE_TAG_FLOAT:
+        case GI_TYPE_TAG_DOUBLE:
+        case GI_TYPE_TAG_GTYPE:
+        case GI_TYPE_TAG_UNICHAR:
+        {
```
Comment (wotzlaff) [inline src/type.cc:304]: Wouldn't it be clearer to just `return true` here? (similarly below)

File: src/value.cc [hunk 4]
```diff
@@ -312,6 +312,46 @@ Local<Value> ArrayToV8 (GITypeInfo *type_info, void* data, long length) {
     return array;
 }
 
+long GIArgumentToLength(GITypeInfo *type_info, GIArgument *arg, bool is_pointer) {
```
Comment (wotzlaff) [inline src/value.cc:315]: Hopefully, this does the right thing. I assume, we are stepping on undocumented GIR ground here again?
Nevertheless this seems at least better than the original line handling it.

File: tests/function_call__inout.js [hunk 5]
```diff
@@ -3,16 +3,42 @@
...
+
+    let position = 3
+    position = editable.insertText(newText, newText.length, position)
+    /* The function updates position to point after the newly inserted text. */
+
+    expect(position, 4)
+    expect(editable.getText(), finalText)
+  })
+
+  // XXX: This one is failing. g_base64_decode_inplace uses inplace data
```
Comment (wotzlaff) [inline tests/function_call__inout.js:30]: Maybe this is worth opening another issue.

File: scripts/preload.js [hunk 6]
```diff
@@ -0,0 +1,10 @@
+/*
+ * preload.js
```
Comment (wotzlaff) [inline scripts/preload.js:2]: What's the purpose of this script?

**Review by wotzlaff — COMMENTED** [review]
I left some comments with open questions. Basically, I support this PR.

File: scripts/preload.js (hunk 6 above)
Comment (romgrk) [reply scripts/preload.js:2]: You can `node -r ./scripts/preload.js` and it drops you in the REPL with gi, gtk and gdk loaded. Maybe it's just me but I do it so often when testing suff out.

File: src/type.cc (hunk 1 above)
Comment (romgrk) [reply src/type.cc:284]: No we're not. I just feel safer with it around. It's such a nice function. But yes I gess I'll remove it.

File: scripts/preload.js (hunk 6 above)
Comment (wotzlaff) [reply scripts/preload.js:2]: Ok. Maybe you could leave such kind a comment somewhere (in the "for maintainers" section?).

File: src/value.cc (hunk 4 above)
Comment (romgrk) [reply src/value.cc:315]: Everywhere is undocumented GIR ground. Everywhere.

But yes, this is more correct because it will work on machines with different endianness. Who knows, maybe someone will try to run node-gtk on a PowerPC.

File: scripts/preload.js (hunk 6 above)
Comment (romgrk) [reply scripts/preload.js:2]: Sure, it has been added

**Comment by wotzlaff** [comment]
Thanks for the changes. I think, you could merge it once you got "green light".
