### PR TITLE
Fix unpacking of boxed from  GValues

### LINKED ISSUE #203: Add support to unpack objects from GValue
Some functions return a `GValue`. Currently, I do not see a possibility to obtain their content if it is an object or boxed.
I will open a pull request to discuss a possible solution.

### PR DESCRIPTION
**Pull request by wotzlaff**
Here's an alternative approach to solve #203. It only handles the special function `getBoxed` of `GValue`. Maybe there are other functions with a similar issue.
The change in `src/value.cc` is necessary to get `setBoxed` working. It might introduce some unwanted side-effects.
I am also not sure about the `mustCopy` argument for `GValueToV8`.

Fixes #203

### CODE REVIEW

File: tests/gvalue__unpack.js [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+  it('should unpack boxed', () => {
+    const color0 = new Gdk.RGBA({ red: 0.5, blue: 0.5, green: 0.5, alpha: 0.5 })
+    const val = new GObject.Value()
+    val.init(GObject.typeFromName('GdkRGBA'))
+    val.setBoxed(color0)
+    expect(color0.toString(), 'rgba(128,128,128,0.5)')
+    const color1 = val.getBoxed()
+    expect(color1.toString(), 'rgba(128,128,128,0.5)')
+  })
+})
```
Comment (romgrk) [inline tests/gvalue__unpack.js:25]: Can we name it `gvalue.js`, and include all GValue tests in this one? The reason for separating things initially was because there were a lot of segfaults so to get error reports on all tests they needed to be separated. Now that it doesn't happen to much, it's ok to centralize a bit. So unless there are like over 10 tests in a single file, it's ok to keep in them in 1.

File: src/modules/system.cc [hunk 2]
```diff
@@ -58,6 +58,16 @@ NAN_METHOD(GetSize) {
...
 }
 
+NAN_METHOD(ConvertGValue) {
+    Local<Object> obj = info[0].As<Object>();
+    if (!ValueHasInternalField(obj)) {
+        RETURN(Nan::Undefined());
+        return;
+    }
+    void *ptr = obj->GetAlignedPointerFromInternalField (0);
+    RETURN(GValueToV8(reinterpret_cast<GValue *>(ptr), false));
```
Comment (romgrk) [inline src/modules/system.cc:68]: Can you add a variable `mustCopy`? It's more readable when you run into it than simply a boolean flag.
Also it will need to be `true` here.

**Comment by romgrk** [comment]
Yes, so I prefer this one, I'll close the other. I've left some comments.

And about `mustCopy`: this flag is only used in the case of Boxed and strings. Other primitive types don't need to worry abou copying, and GObjects have their own ref/unref mechanism, along with JS Weak Callbacks to free them when the corresponding JS Object Handle is garbage-collected. For GObjects, there is always one single JS Object for one GObject, and GObjects have a unique identity. The same GObject is never referred to by different instances, you simply have many references (pointers) to a single GObject structure.

For Boxeds however, they are more like a bag of data and don't necessarily have a concept of unique identity. See [Value Objects](https://en.wikipedia.org/wiki/Value_object#:~:text=In%20computer%20science%2C%20a%20value,money%20or%20a%20date%20range.) on wikipedia. For example, a GdkRGBA is used to refer not to an instance of GdkRGBA, but to refer to the color itself. What this means is that 99% of the time, the correct behavior for a Boxed will be to make a copy. This is also easier for us because then the `Box->owns_memory` is true, and we know we should simply destroy it when the JS Object Handle is GC'ed.
There is however a few rare cases when it is required to NOT make a copy of the Boxed. One such example is output parameters which pass a Boxed. For example, the `"get-child-position"` signal on `GtkOverlay` passes as arguments `(widget: GtkWidget, allocation: GdkRectangle)` to a function. This function needs to modify `allocation` in-place to let the `GtkOverlay` where to position a children. In this case, if we were to make a copy it wouldn't work because the data wouldn't be written in the output parameter structure. But this is obviously way less safer, because the `GdkRectangle` lifetime is only valid for the duration of the signal call. So if the JS code was to somehow save a reference to the `allocation` JS Object during that function call and use it at some later point, it would wreak havoc. This issue is currently not hanlded AFAIK.

So this is it for the `mustCopy` flag, hope it helps, don't hesitate to ask questions if you have some.

And for the PR once the comments are done it looks good to me.

**Comment by wotzlaff** [comment]
Thanks for your explanation. Now I understand the `mustCopy` flag a bit better.
Also thanks for your continuous support. Without your helpful comments I probably would not have gone so far :)

**Comment by romgrk** [comment]
Sorry for the delay, I had been dealing with depression for some time and had to take vacations away from technology to clear my mind :/ I'm back now and will review the other blocked PRs this week :)

**Comment by wotzlaff** [comment]
Hey, welcome back. Please don't hurry. I'm fine with waiting ;)
