### PR TITLE
Fix cairo macos

### LINKED ISSUE #233: Cairo fails to load Arial font on recent macOS version
See https://github.com/romgrk/node-gtk/pull/230#issuecomment-717858019

We need to find out why the status is `Cairo.Status.INVALID_STRING`. Maybe there's something which needs to be installed since the issue does not occur on travis.

> font.status() from const font = Cairo.FontFace.create('Arial', Cairo.FontSlant.OBLIQUE, Cairo.FontWeight.BOLD) is Cairo.Status.INVALID_STRING instead of Cairo.Status.SUCCESS. This issue is not present in travis.

### PR DESCRIPTION
**Pull request by romgrk**
Closes #233

### CODE REVIEW

**Comment by romgrk** [comment]
This should be ready for review @wotzlaff if you're up for it.

File: src/modules/cairo/generator.js [hunk 1]
```diff
@@ -415,7 +415,7 @@ function getInArgumentSource(p, n) {
     return `auto ${p.name} = Nan::To<int64_t>(info[${n}].As<Number>()).ToChecked();`
 
   if (typeName === 'const char *')
-    return `auto ${p.name} = *Nan::Utf8String (info[${n}].As<String>());`
+    return `auto ${p.name}__value = info[${n}].As<String>(); auto ${p.name} = *Nan::Utf8String(${p.name}__value);`
```
Comment (wotzlaff) [inline src/modules/cairo/generator.js:418]: It is still not working: The `Nan::Utf8String` has no name and gets freed too soon.

It should be something like this:
```js
return `Nan::Utf8String ${p.name}__value(info[${n}].As<String>()); auto ${p.name} = *${p.name}__value;`
```

(I haven't tried the generation script, yet. But that's what my modification in the code would look like.)

Another small thing: Would it be possible to add a newline (and proper indentation) there?

**Review by wotzlaff — CHANGES_REQUESTED** [review]

File: src/modules/cairo/generator.js (hunk 1 above)
Comment (romgrk) [reply src/modules/cairo/generator.js]: Updated.

For the indentation, it would require more work that I can do at the moment. Some parts of the generator are able to return array of lines that get indented correctly, but overall indentation is messy and would need more work.

**Review by wotzlaff — APPROVED** [review]
Seems fine now.
The tests are passing on macOS 10.15.7.

**Comment by romgrk** [comment]
:+1:
